language: android
jdk:
    - oraclejdk8
    - openjdk7

before_install:
    - chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - sys-img-x86-android-22